env:
    browser: true
overrides:
    - files:
        - "*.ts"
      env:
        es6: true
      extends:
        - eslint:recommended
        - plugin:@typescript-eslint/eslint-recommended
        - plugin:@typescript-eslint/recommended
        - plugin:@typescript-eslint/recommended-requiring-type-checking
        - prettier
      parser: "@typescript-eslint/parser"
      parserOptions:
        ecmaVersion: 2018
        project: tsconfig.json
        sourceType: module
      rules:
        "@typescript-eslint/no-unused-vars":
          - error
          - args: all
            argsIgnorePattern: ^_
